翻译 3_801-1197
ApolloZhu/Developing-iOS-10-Apps-with-Swift pull request #10
Opened 2017-04-28 13:32 UTC by superk589

2017-04-28 14:47 UTC, ApolloZhu commented
我会尽快过一遍，先让我把之前的那个 pull requests 处理了

2017-04-28 14:50 UTC, superk589 commented
好 不急

2017-05-06 19:03 UTC, ApolloZhu requested changes
感觉非常好，谢谢！因为我的原因拖了很久，挺不好意思的。
把 pull request merge 之后你再看有没有要改的，完了还是给我说一声。

2017-05-07 03:49 UTC, superk589 commented
完事了 结果还是犯了不少低级错误...以后要更加注意了
修改的部分
1. 代表一个独立字符串的部分 还是和中文隔开一个空格 和其他部分保持统一
2. "对比如包含逗号或者其他分隔字符的字符串" 感觉有歧义 因为"对比"也可以视作一个词, 可能不会被理解为"对   比如..." 直接把比如删掉也很通顺

2017-05-07 03:58 UTC, ApolloZhu approved these changes

2017-05-07 03:59 UTC, ApolloZhu commented
好，谢谢了！错误谁都有，但是这次明显感觉比上次好很多呢！

2017-05-07 04:00 UTC, merged