翻译
ApolloZhu/Developing-iOS-10-Apps-with-Swift pull request #24
Opened 2017-08-10 10:34 UTC by gitgitcode

## 类型
- [x] 翻译
- [ ] 校对
- [ ] 其他

集数：#4-5
开始段：#
结束段：#

备注（如果有，请列出）：
- 没有则不填

2017-08-10 13:45 UTC, ApolloZhu commented
> <del>1. 为什么修改文件名？</del>
>
> <del>先不说其他的，现在第四集和第五集是属于部分翻译的状态，更改文件名会多半会导致合并回主分支的时候出问题，所以如果可能的话请改回原来的命名。</del>

带着这些疑问，我看了看好像是机器翻译了 4、5、6 三集？如果是的话建议您
- 参考 [翻译标准／校对规则](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/translation-style-guide.md) 更正第六集的翻译
  - 第四、五集保留目前的人工翻译
  - 请把从翻译平台上下载的文件改回原来的名字
- 因为机器翻译是整个文件，作为例外可以不用依照 [任务相关说明](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/.github/CONTRIBUTING.md)

如果您只是需要机器翻译的版本，参见 @iam36[/Translate-Developing-iOS-10-Apps-with-Swift](https://github.com/iam36/Translate-Developing-iOS-10-Apps-with-Swift)

2017-08-10 13:48 UTC, ApolloZhu requested changes
1. 撤销对文件重命名
2. 更正机器翻译错误

2017-08-11 03:10 UTC, gitgitcode commented
谢谢回复。
- 是的，这部分是机器翻译的，简单看了一下大部分正确。
我刚看到第三集，所以先把后面的内容用工具翻译了，想在看的时候边看边校对。
- 规整文件名字是为了在不同的系统和平台下方便系统使用，同时也有利于人的阅读。
- 提交的原因是因为没有发现全部翻译完的项目，如果提交出来当有人找到这里时或许可以应急用。@iam36 的版本我可拿来自己使用。
- 目前来看我主要以过视频学习为主，并不能专注于按照规范把整体翻译，如果我的进度快于你们的翻译进度的话我再提交吧，这个可以被关闭撤销了。

2017-08-11 04:51 UTC, ApolloZhu commented
1. 其实字幕文件名是和视频文件名保持一致的。个人感觉更接近于自然语言，用下划线更接近于命令行的习惯
2. 我之后会把全部机器翻译的链接加到 README
3. 那我就先关了，如果您之后有翻译可以按照正常程序再提交

2017-08-11 04:51 UTC, closed without merging

2017-08-11 07:30 UTC, gitgitcode commented
好