字体部分改为黑色
ApolloZhu/Developing-iOS-10-Apps-with-Swift pull request #26
Opened 2017-08-15 08:14 UTC by snowdenfu

Xcode背景下白色字体看不见，改为黑色

## 类型
- [x] 翻译
- [ ] 校对
- [ ] 其他

集数：#
开始段：#
结束段：#

备注（如果有，请列出）：
- 没有则不填

2017-08-15 08:53 UTC, ApolloZhu commented
## 给百度云那里加括号是对的，很好，可以留下
## 不过黑体字这个。。。能通过播放器设置吗？我的播放器(VLC, IINA)默认加了黑边，看起来是这样
<img src="https://user-images.githubusercontent.com/10842684/29308855-f599b6b0-816c-11e7-8860-f70363e45d41.png" height = 256 />

## 所以设为黑色之后容易模糊成一团
<img src="https://user-images.githubusercontent.com/10842684/29308491-a48132e0-816b-11e7-8e81-5d87d12ce996.png" height = 256 />

2017-08-16 03:21 UTC, snowdenfu commented
加黑边的好啊，但是我的就没有，啥也看不见，有没有一种通用的方法呢，我看原视频有黑色背景的也不错

2017-08-16 03:38 UTC, ApolloZhu commented
这个真的看播放器了... 一般都可以设置的吧？您用的什么播放器？

没记错的话苹果系统在可以在辅助功能里更改设置
我上传到 B 站的弹幕自带黑边（上传的时候可以调参数，程序暂不支持从 srt 读取格式）
Youtube 上别人搬运的原版好像是加底色（也可以设置）

2017-08-16 08:08 UTC, snowdenfu commented
真的耶，谢谢

2017-08-16 08:32 UTC, ApolloZhu commented
(・ o ・) 好吧。那您要不考虑修改一下，只提交百度云那一行的更改？

2017-08-16 08:36 UTC, snowdenfu commented
行啊，你说的算啊。你太客气了，我是学软件专业的，字幕方面我也是刚刚接触，不太懂

2017-08-16 08:55 UTC, ApolloZhu commented
没关系。
修改后 commit 会自动合并到这个 pull request 里，到时候我直接合并。

2017-08-16 08:58 UTC, ApolloZhu requested changes
只保留对第 192 条的修改，revert 对文字颜色的限制

2017-09-10 18:14 UTC, closed without merging