4_129-500, 4_1401-1894 翻译
ApolloZhu/Developing-iOS-10-Apps-with-Swift pull request #28
Opened 2017-08-19 07:16 UTC by VoiceBeer

## 类型
- [x] 翻译
- [ ] 校对
- [ ] 其他

集数：4.Views
开始段：633, 1363
结束段：900, 1399

备注（如果有，请列出）：
- 没有则不填

2017-08-19 21:06 UTC, ApolloZhu requested changes
一个人把第四集翻译完了很厉害！谢谢！

刚刚过完了，估计因为只是一部分的翻译，可能没有前后的对照，有部分理解错误的地方我就改过来了。同时还修改了部分时间轴和英文字幕，你可以再看看还有没有什么要改的地方，认为可以合并了的话通知我一声。

备注：GitHub 允许我直接 push，所以你就没有需要 merge 的 pull request 了

2017-08-20 01:34 UTC, VoiceBeer commented
谢谢！

我看了下，的确是有很多错误，都有点不好意思了。
之后的翻译会注意，时间轴和英文字幕也会注意改（我还以为这个不要动呢）
应该可以合并了，另外已经已经向你发了协作者的邀请，应该是你备注里的意思吧？

2017-08-20 01:53 UTC, ApolloZhu commented
好吧，那就这样吧。

英文有问题的是要改的（[错误修正 第一条](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/translation-style-guide.md#错误修正)）
我备注的意思是不用管 [这里的第四条](https://github.com/ApolloZhu/Developing-iOS-10-Apps-with-Swift/blob/master/CONTRIBUTING.md#提交翻译)，邀请就不用了

2017-08-20 01:53 UTC, ApolloZhu approved these changes

2017-08-20 01:54 UTC, merged

2017-08-20 01:57 UTC, VoiceBeer commented
好的，之后我会注意的，辛苦你啦