2_400-799 翻译
ApolloZhu/Developing-iOS-10-Apps-with-Swift pull request #9
Opened 2017-04-26 06:51 UTC by lianfanghua

2017-04-26 10:15 UTC, ApolloZhu commented
明天有考试，今天需要临时抱佛脚。明天考完了我看看

2017-04-29 03:41 UTC, ApolloZhu requested changes
以后有空可以自己先对着视频过一遍。
你把你那边的 pull request merge 之后再看看有没有什么要改的，完了给我说一声。

2017-04-29 03:41 UTC, ApolloZhu commented on subtitles/2. MVC; iOS, Xcode and Swift Demonstration.srt
> +这是绿色通道，连通
这个翻译的好！很形象！

2017-05-01 03:29 UTC, ApolloZhu approved these changes

2017-05-01 03:39 UTC, lianfanghua commented
@ApolloZhu 已经看过了，没问题，你翻译得很好，很有味道，谢谢指点。

2017-05-01 03:43 UTC, merged